### ISSUE TITLE
Not creating correct files for emuiibo

### ISSUE THREAD

**Issue by jon-daemon** [midyro/emiibo-mac#1]
The files created are not recognized by emuiibo.
I used an app on switch (AmiiboGenerator.nro) to create some amiibos and they work fine. It created these files:
```
amiibo.flag
amiibo.json
amiibo.png
areas.json
mii-charinfo.bin
```
Do you still maintain it? Is it possible to fix that?

**Comment by midyro** [comment]
I haven't touched this project in years and I'm not planning to maintain the code. I'm going to archive the project, but feel free to create a fork or use other projects.
